<?php

/*
* Implements hook_entity_info_alter().
*/
function noreg_content_types_entity_info_alter(&$entity_info) {

  // List
  $entity_info['node']['view modes']['list'] = array(
    'label'           => t('List'),
    'custom settings' => TRUE,
  );

  // Includeable
  $entity_info['node']['view modes']['includeable'] = array(
    'label'           => t('Includeable'),
    'custom settings' => TRUE,
  );
}
