<?php

/**
 * Implements hook_field_formatter_info().
 */
function noreg_raw_text_field_formatter_field_formatter_info() {
  return array(
    'text_raw' => array(
      'label' => t('Raw output'),
      'field types' => array('text', 'text_long', 'text_with_summary'),
    ),
  );
}

/**
 * Implements hook_field_formatter_view().
 */
function noreg_raw_text_field_formatter_field_formatter_view($entity_type, $entity, $field, $instance, $langcode, $items, $display) {
  $element = array();
  switch ($display['type']) {

    case 'text_raw':
      foreach ($items as $delta => $item) {
        $element[$delta] = array(
          '#markup' => $item['value'],
        );
      }
      break;
  }

  return $element;
}

/**
 * Implements template_preprocess_field().
 */
function noreg_raw_text_field_formatter_preprocess_field(&$variables, $hook) {
  $element = $variables ['element'];

  $variables['theme_hook_suggestions'][] = 'field__' . $element ['#formatter'];
  $variables['theme_hook_suggestions'][] = 'field__' . $element ['#field_type'] . '__' . $element ['#formatter'];
}

/**
 * Implements hook_theme_registry_alter().
 */
function noreg_raw_text_field_formatter_theme_registry_alter(&$theme_registry) {
  // Defined path to the current module.
  $module_path = drupal_get_path('module', 'noreg_raw_text_field_formatter');
  // Find all .tpl.php files in this module's folder recursively.
  $template_file_objects = drupal_find_theme_templates($theme_registry, '.tpl.php', $module_path);
  // Iterate through all found template file objects.
  foreach ($template_file_objects as $key => $template_file_object) {
    // If the template has not already been overridden by a theme.
    if (!isset($theme_registry[$key]['theme path']) || !preg_match('#/themes/#', $theme_registry[$key]['theme path'])) {
      // Alter the theme path and template elements.
      $theme_registry[$key]['theme path'] = $module_path;
      $theme_registry[$key] = array_merge($theme_registry[$key], $template_file_object);
      $theme_registry[$key]['type'] = 'module';
    }
  }
}
